### ISSUE TITLE
Current problems

### ISSUE THREAD

**Issue by isAlenz** [1900Star/MusicPlayer-Smartisan#7]
1.only have favorite_db, so create a new playlist doesn't work
2.can't search lyrics online because api is out
3.compare with other musicplayer , this project can't change background, but it has some star points, such as back up favorite songs
4.when click delete wrong lyrics function , app will crash
5.crash log doen't work

maybe have something else , I will update on time

**Comment by 1900Star** [comment]
Thank you for your feedback. I am restructuring this project. I have completed part of it and will continue to update it later. You can pay attention to the branch masterA, which fixes the problems you feed back. Apart from the second one, because there is no free lyrics provider, I temporarily closed the online search of lyrics.
